apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-apps-set
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - appName: students-api
            repoURL: https://github.com/Sampanionyy/students-api.git
          - appName: pdf-viewer
            repoURL: https://github.com/Sampanionyy/pdf-viewer.git

  template:
    metadata:
      name: '{{appName}}'

    spec:
      project: default

      source:
        repoURL: '{{repoURL}}'
        targetRevision: main
        path: first-chart   

        helm:
          valueFiles:
            - values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: default

      syncPolicy:
        automated:
          prune: true
          selfHeal: true